apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-custom
spec:
  version: 8.10.4
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
        storageClassName: local-storage
    # podTemplate:
    #   spec:
    #     containers:
    #     - name: elasticsearch
    #       env:
    #       - name: ES_JAVA_OPTS
    #         value: -Xms1g -Xmx1g
    #       resources:
    #         requests:
    #           memory: 2Gi
    #           cpu: 0.5
    #         limits:
    #           memory: 2Gi
    #           cpu: 2

  http:
    tls:
      selfSignedCertificate:
        disabled: true