apiVersion: v1
kind: PersistentVolume
metadata:
  # pv是没有namespace属性的，它是一种跨namespace的共享资源
  name: pv-1gi
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/d/wsl/nfs/data/01
  nodeAffinity:
    required:
      nodeSelectorTerms: 
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  # pv是没有namespace属性的，它是一种跨namespace的共享资源
  name: pv-2gi
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/d/wsl/nfs/data/02
  nodeAffinity:
    required:
      nodeSelectorTerms: 
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  # pv是没有namespace属性的，它是一种跨namespace的共享资源
  name: pv-5gi
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/d/wsl/nfs/data/03
  nodeAffinity:
    required:
      nodeSelectorTerms: 
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  # pv是没有namespace属性的，它是一种跨namespace的共享资源
  name: pv-10gi
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/d/wsl/nfs/data/04
  nodeAffinity:
    required:
      nodeSelectorTerms: 
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  # pv是没有namespace属性的，它是一种跨namespace的共享资源
  name: pv-15gi
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /run/desktop/mnt/host/d/wsl/nfs/data/15
  nodeAffinity:
    required:
      nodeSelectorTerms: 
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
