apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogo
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gogo
  template:
    metadata:
      labels:
        app: gogo
    spec:
      containers:
        - name: gogo-container
          image: gogo:v1.0
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gogo-svc
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30066
  selector:
    app: gogo